name: Build With Multiple NodeJS Versions

on:
  pull_request:
    branches:
      - compiler # run when this branch pull requested
  push:
    branches:
      - compiler # run when this branch pushed

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 13.x, 14.x]
    env:
      NODE_OPTIONS: "--max_old_space_size=4096" #8192
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Get Cache NPM dependencies
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules
            ./docs
            ~/.npm
          key: |
            ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-yarn-
      - run: sudo apt-get install libcurl4-openssl-dev
      - id: npm-install
        continue-on-error: true
        run: npm i -g npm hexo-cli gulp-cli typescript ts-node && npm ci
      - name: install additional dependencies
        run: npm i git+https://github.com/dimaslanjaka/hexo-blogger-xml.git git+https://github.com/dimaslanjaka/hexo-seo.git git+https://github.com/dimaslanjaka/hexo-adsense.git

      #### ONLY RUN BELOW RUNNER IF ABOVE INSTALLATIONS SUCCEEDED ####
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd themes/material && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: npx gulp article:copy
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: hexo generate
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd docs/page && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        name: Userscripts
        run: |
          node userscripts/custom-domain.js
          node userscripts/copy.js
          node userscripts/after_generated.js
          node userscripts/validate.js

