name: Build And Tests

on:
  pull_request:
    branches:
      - compiler # run when this branch pull requested
  push:
    branches:
      - compiler # run when this branch pushed

# cancel previous workflows, run only one workflow
concurrency:
  group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build www.webmanajemen.com
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192 4096 --expose-gc
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Get Cache NPM dependencies
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules
            ~/.npm
            ./tmp
            ./build
          key: ${{ runner.os }}-nodejs-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-nodejs-
      - run: npm i -g npm hexo-cli gulp-cli typescript ts-node
        # run global install when cache not found
        if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: rm -rf node_modules tmp build
        # run if commit contains substring 'clean cache'
        if: "contains(github.event.head_commit.message, 'clean cache')"
      - run: npm install
      #- run: npm i hexo-seo hexo-blogger-xml hexo-adsense
      - run: cd themes/material && npm install
      - run: npx gulp article:copy
      - run: hexo clean
        # run if commit contains substring 'clean cache'
        if: "contains(github.event.head_commit.message, 'clean cache')"
      - run: hexo generate
        id: hexo-g
      - run: cd docs/page && npm install
      - name: Userscripts
        run: |
          node userscripts/custom-domain.js
          node userscripts/copy.js
          node userscripts/after_generated.js
          node userscripts/validate.js

      - name: Deploy 🚀
        if: steps.hexo-g.outcome == 'success' && steps.hexo-g.conclusion == 'success'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.

      - name: Deploy to firebase
        # deploy if commit message contains firebase string
        if: "contains(github.event.head_commit.message, 'firebase') && steps.hexo-g.outcome == 'success' && steps.hexo-g.conclusion == 'success'"
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANDROID_008 }}"
          channelId: live
          projectId: android-008

  test-npm-package:
    if: ${{ false }} # disable
    name: Test Build With NPM Packages
    #needs: build
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 13.x, 14.x]
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: npm-install
        continue-on-error: true
        run: npm i -g npm hexo-cli gulp-cli typescript ts-node && npm ci
      - name: install additional dependencies
        id: npm-install-submodules
        continue-on-error: true
        #run: npm i git+https://github.com/dimaslanjaka/hexo-blogger-xml.git git+https://github.com/dimaslanjaka/hexo-seo.git git+https://github.com/dimaslanjaka/hexo-adsense.git
        run: npm i hexo-seo hexo-blogger-xml hexo-adsense

      #### ONLY RUN BELOW RUNNER IF ABOVE INSTALLATIONS SUCCEEDED ####
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd themes/material && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: npx gulp article:copy
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: hexo generate
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd docs/page && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        name: Userscripts
        run: |
          node userscripts/custom-domain.js
          node userscripts/copy.js
          node userscripts/after_generated.js
          node userscripts/validate.js

  test-git-package:
    #if: ${{ false }} # disable
    name: Test Build With GIT Packages
    #needs: test-npm-package
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymax-parallel
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x, 14.x]
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - id: npm-install
        continue-on-error: true
        run: npm i -g npm hexo-cli gulp-cli typescript ts-node && npm ci
      - name: install additional dependencies
        id: npm-install-submodules
        continue-on-error: true
        run: npm i git+https://github.com/dimaslanjaka/hexo-blogger-xml.git git+https://github.com/dimaslanjaka/hexo-seo.git git+https://github.com/dimaslanjaka/hexo-adsense.git
        #run: npm i hexo-seo hexo-blogger-xml hexo-adsense

      #### ONLY RUN BELOW RUNNER IF ABOVE INSTALLATIONS SUCCEEDED ####
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd themes/material && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: npx gulp article:copy
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: hexo generate
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        run: cd docs/page && npm install
      - if: steps.npm-install.outcome == 'success' && steps.npm-install.conclusion == 'success'
        name: Userscripts
        run: |
          node userscripts/custom-domain.js
          node userscripts/copy.js
          node userscripts/after_generated.js
          node userscripts/validate.js

